<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommande ($idCommande){
        
        $qb = $this
            ->createQueryBuilder('b')
            ->innerJoin('b.commande', 'com')
            ->innerJoin('com.facturation', 'fac')
            ->addSelect('com')
            ->addSelect('fac')
            ->where('b.commande = :idCommande')
            ->setParameter('idCommande', $idCommande);

        return $qb
            ->getQuery()
            ->getResult();
        
        
    }    
}
