<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function renvoiBillet ($courriel){
        
        $qb = $this
            ->createQueryBuilder('c')
            ->innerJoin('c.facturation', 'fac')
            ->addSelect('fac')
            ->where('fac.courriel = :courriel')
            ->setParameter('courriel', $courriel);

        return $qb
            ->getQuery()
            ->getResult();
        
    }
}
