# src/Louvre/BilletterieBundle/Resources/config/routing.yml

louvre_core_homepage:
    path:     /
    defaults: 
        _controller: LouvreBilletterieBundle:Billetterie:formacc

louvre_billetterie_validation:
    path:   /validation
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:validation

louvre_billetterie_paiement:
    path:    /paiement
    defaults: 
        _controller: LouvreBilletterieBundle:Billetterie:paiement
        
louvre_stripe:
    path:   /paiement/stripe
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:prepareStripe
    
louvre_paypal_express_checkout:
    path:   /paiement/paypal
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:preparePaypal
        
louvre_payment_done:
    path:   /paiement/remerciement
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:done
