# src/Louvre/BilletterieBundle/Resources/config/routing.yml

louvre_core_homepage:
    path:     /
    defaults: 
        _controller: LouvreBilletterieBundle:Billetterie:formacc

louvre_billetterie_paiement:
    path:    /paiement
    defaults: 
        _controller: LouvreBilletterieBundle:Billetterie:paiement
        
louvre_payment_done:
    path:   /remerciement
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:done
        
louvre_billet_recover:
    path:   /recover
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:recover

louvre_billetterie_contact:
    path:   /contact
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:contact
        
louvre_billetterie_infos:
    path:   /info-pratique
    defaults:
        _controller: LouvreBilletterieBundle:Billetterie:info